luna/blog/urls.py
from django.urls import path
from . import views 
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='posts_feed'),
    path('search/', views.post_search, name='post_search'),
]

luna/luna/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap 
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace="blog")),
    path('shop/', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

luna/blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth import get_user_model
from django.urls import reverse
from taggit.managers import TaggableManager


User = get_user_model()

# Create your models here.

class DraftsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.DRAFT
        )
    

class ReviewsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.REVIEW
        )
    

class ApprovedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.APPROVED
        )
    

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.PUBLISHED
        )
    




class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        REJECT = "RJ", "Rejected"
        REVIEW = 'RW', 'Under review'
        APPROVED = "AP", "Approved"
        PUBLISHED = 'PB', 'Published'
        
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
        User,
        related_name='blog_posts',
        on_delete=models.CASCADE
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager()
    drafts = DraftsManager()
    under_review = ReviewsManager()
    approved = ApprovedManager()
    published = PublishedManager()
    tags = TaggableManager()
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta: 
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created']),

        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post} sSse efsfsee'

luna/blog/forms.py
from django import forms 
from .models import Comment 


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )
    # opt_in = forms.CheckboxInput



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']



class SearchForm(forms.Form):
    query = forms.CharField()

luna/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.core.mail import send_mail 
from django.db.models import Count 
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None 
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug
        )
        post_list = post_list.filter(tags__in=[tag])
    
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)

    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag
        }
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=post
    )
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publish'
    )[:4]
    
    comments = post.comments.filter(active=True)
    form = CommentForm()

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post, 
            'comments': comments, 
            'form': form,
            'similar_posts': similar_posts
        }
    )


def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    sent = False 
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data 
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )

            subject = f'{cd["name"]} recommends "{post.title }"'
            message = f'''
                Read "{ post.title }" at {{ post_url }}\n\n{ cd["name"]}\'s comments: { cd["comments"] }
            '''
            send_mail(subject, message, settings.DRIP_EMAIL_SENDER, [cd["to"]])
            sent = True

    else:
        form = EmailPostForm()
    return render(
        request, 
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None 
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )



def post_search(request):
    form = SearchForm()
    query = None 
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight="A") + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            "query": query,
            'results': results
        }
    )

luna/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
    {% if comment %}
    <h2 class="title is-2 has-text-centered">
        Comment published
    </h2>
    <hr>
    <div class="notification is-large is-success is-light">
        <a class="delete" href="{{ post.get_absolute_url }}"></a>
        <p class="indented">Your comment has been successfully published.</p>
        <p class="indented">Exit this message to return to the original post.</p>
    </div>
    {% else %}
    <h2 class="title is-2 has-text-centered">
        Add a comment
    </h2>
    <hr>
    {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

luna/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load content_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h2 class="title is-2 has-text-centered has-text-white">
    {{ post.title }}
</h2>
<p class="subtitle has-text-centered has-text-white">
    Published {{ post.publish }} by {{ post.author }}.
</p>
<hr>
<div class="content has-text-white box has-background-info-dark">
    {{ post.body|article:"has-text-white"|markdown }}
</div>
<div class="buttons is-centered">
    <a class="button is-info is-large is-block has-text-centered" href="{% url 'blog:post_share' post.id %}">Share article</a>
</div>
<hr>
{% with comments.count as total_comments %}
<div class="column">
    <h4 class="title has-text-centered has-text-white">
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h4>

{% endwith %}
{% for comment in comments %}
<div class="card has-background-{% cycle 'primary-dark' 'info-dark' %} m-auto">
    <div class="card-header">
        <div class="card-header-title has-text-white">
            {{ comment.name }}
        </div>
        <p class="has-text-white has-text-weight-light is-size-7">@ {{ comment.created }}</p>
    </div>
    <div class="card-content has-text-white">
        {{ comment.body|article:"has-text-white" }}
    </div>
</div>
<br>
{% empty %}
<div class="notification is-info">
    There are no comments to show.
</div>
{% endfor %}
<hr>
{% include "blog/post/includes/comment_form.html" %}
</div>
{% endblock %}

{% block sidenav %}
<h4 class="menu-label has-text-white">Similar posts</h4>
<ul class="menu-list">
    {% for post in similar_posts %}
    <li><a class="has-text-white" href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% empty %}
    <li><p><strong>There are no similar posts to show.</strong></p></li>
    {% endfor %}
</ul>
{% endblock %}

luna/blog/templates/blog/post/latest_posts.html
<h4 class="menu-label has-text-white">
    Latest Posts
</h4>
<ul class="menu-list">
    {% for post in latest_posts %}
    <li><a class="has-text-white" href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

luna/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load content_tags %}
{% block title %}Musings{% endblock %}
{% block content %}
<h2 class="title is-2 has-text-centered has-text-white">Recent Musings</h2>
{% if tag %}
<span class="subtitle tag is-primary is-large">{{ tag.name }}</span>
{% endif %}
<hr>
{% for post in posts %}
<div class="card has-background-primary-dark">
    <div class="card-header has-background-info-dark">
        <a class="card-header-title has-text-white is-size-4" href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        <p class="has-text-weight-light has-text-white is-size-7 mr-2 mt-2">Published {{ post.publish }} by {{ post.author }}</p>
    </div>
    <div class="card-content">
        <div class="tags is-right">
            {% for tag in post.tags.all %}
            <a class="tag is-{% cycle 'primary' 'danger' 'info' 'warning' 'link' 'success' 'black' %}" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% endfor %}
            {% resetcycle %}
        </div>

        <div class="content has-text-white has-text-weight-semibold">
            {{ post.body|article|markdown|truncatewords_html:30 }}
        </div>
    </div>
</div>
<br>
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

luna/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load content_tags %}
{% block title %}Share this post{% endblock %}
{% block content %}
    {% if sent %}
    <h2 class="title is-2 has-text-centered has-text-white">Post shared</h2>
    <hr>
    <div class="notification is-large is-success">
        <a class="delete" href="{% url 'blog:post_list' %}"></a>
        <p class="indented">Post has been successfully shared to <strong>{{ form.cleaned_data.to }}</strong></p>
    </div>
    {% else %}
    <h2 class="title is-2 has-text-centered has-text-white">Share <em>{{ post.title }}</em></h2>
    <p class="subtitle has-text-centered has-text-white">Send this post to you or someone else via e-mail</p>
    <hr>
    <div class="column box has-background-info-dark is-half is-offset-one-quarter">
        <form method="post">
            {% csrf_token %}
            {{ form|bulma_form:"has-text-white" }}
            <div class="field">
                <div class="control">
                    <input type="submit" value="Share" class="button  is-white is-outlined is-block is-fullwidth has-text-centered">
                </div>
            </div>
        </form>
    </div>
    {% endif %}
{% endblock %}