luna/blog/urls.py
from django.urls import path
from . import views 
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='posts_feed'),
    path('search/', views.post_search, name='post_search'),
]

luna/luna/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap 
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace="blog")),
    path('shop/', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

luna/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

luna/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name 
    
    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category',
            args=[self.slug]
        )
    


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d/',
        blank=True
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name 
    
    def get_absolute_url(self):
        return reverse(
            'shop:product_detail',
            args=[self.id, self.slug]
        )

luna/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


# Create your views here.

def product_list(request, category_slug=None):
    category = None 
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(
            Category,
            slug=category_slug
        )
        products = products.filter(category=category)
    
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products
        }
    )


def product_detail(request, id, slug):
    product = get_object_or_404(
        Product,
        id=id,
        slug=slug,
        available=True
    )
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
        }
    )

luna/shop/templates/shop/base.html
{% load static content_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tenor+Sans">
        <style>
            body {
                font-family: "Tenor Sans";
                background-color: #232323;
            }
            input.input, .textarea {
                background-color: #232323;
                color: #dfdfdf;
            }
            p.indented {
                text-indent: 30px
            }
            aside.menu li a:hover {
                background-color: #232323;
            }
        </style>
    </head>
    <body>
        <nav class="navbar is-black">
            <div class="navbar-brand">
                <a class="navbar-item" href="/shop/">
                    <img src="{% static 'imgs/logo.png' %}" alt="Logo" width="112" height="28">
                </a>
                <div class="navbar-burger burger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'shop:product_list' %}">Store</a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link" href="#">
                        Lunas Chambers
                    </a>
                    <div class="navbar-dropdown is-boxed">
                        <a class="navbar-item" href="{# url 'blog:post_list' %}">Luna's Musings</a>
                        <a class="navbar-item" href="#">Contact Luna</a>
                    </div>
                </div>
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a class="button is-primary">s</a>
                        </p>
                    </div>
                </div>
            </div>
        </nav>
        <section class="hero is-info is-medium">
            <div class="hero-body">
                <div class="container">
                    <h4 class="title is-4">$0.00</h4>
                    <p class="subtitle has-text-weight-semibold">Your cart is empty.</p>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="container">
                <div class="columns is-centered">
                    <div class="column is-9 has-text-centered">
                        {% block content %}
                        {% endblock %}
                    </div>
                    <div class="column is-3">
                        <div class="buttons">
                            <a class="button is-block is-large is-fullwidth is-warning" href="#">Checkout</a>
                        </div>
                        <aside class="menu box has-background-black">
                            {% block sidenav %}
                            {% endblock %}
                        </aside>
                    </div>
                </div>
            </div>
        </section>

        <footer class="footer has-background-black">
            <div class="container has-text-centered has-text-white">
                <p>Hello world</p>
            </div>
        </footer>
        <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
        <script>
            const csrftoken = Cookies.get('csrftoken');
            document.addEventListener('DOMContentLoaded', () => {
                (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
                    const $notification = $delete.parentNode;

                    $delete.addEventListener('click', () => {
                        $notification.parentNode.removeChild($notification);
                    });
                });
                {% block domready %}
                {% endblock %}
            });
        </script>
        {% block extra_js %}
        {% endblock %}
    </body>
</html>