luna/blog/urls.py
from django.urls import path
from . import views 
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='posts_feed'),
    path('search/', views.post_search, name='post_search'),
]

luna/luna/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap 
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace="blog")),
    path('shop/', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

luna/blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth import get_user_model
from django.urls import reverse
from taggit.managers import TaggableManager


User = get_user_model()

# Create your models here.

class DraftsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.DRAFT
        )
    

class ReviewsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.REVIEW
        )
    

class ApprovedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.APPROVED
        )
    

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.PUBLISHED
        )
    




class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        REJECT = "RJ", "Rejected"
        REVIEW = 'RW', 'Under review'
        APPROVED = "AP", "Approved"
        PUBLISHED = 'PB', 'Published'
        
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
        User,
        related_name='blog_posts',
        on_delete=models.CASCADE
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager()
    drafts = DraftsManager()
    under_review = ReviewsManager()
    approved = ApprovedManager()
    published = PublishedManager()
    tags = TaggableManager()
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta: 
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created']),

        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post} sSse efsfsee'

luna/blog/forms.py
from django import forms 
from .models import Comment 


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )
    # opt_in = forms.CheckboxInput



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']



class SearchForm(forms.Form):
    query = forms.CharField()

luna/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.core.mail import send_mail 
from django.db.models import Count 
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None 
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug
        )
        post_list = post_list.filter(tags__in=[tag])
    
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)

    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag
        }
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=post
    )
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publish'
    )[:4]
    
    comments = post.comments.filter(active=True)
    form = CommentForm()

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post, 
            'comments': comments, 
            'form': form,
            'similar_posts': similar_posts
        }
    )


def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    sent = False 
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data 
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )

            subject = f'{cd["name"]} recommends "{post.title }"'
            message = f'''
                Read "{ post.title }" at {{ post_url }}\n\n{ cd["name"]}\'s comments: { cd["comments"] }
            '''
            send_mail(subject, message, settings.DRIP_EMAIL_SENDER, [cd["to"]])
            sent = True

    else:
        form = EmailPostForm()
    return render(
        request, 
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None 
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )



def post_search(request):
    form = SearchForm()
    query = None 
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight="A") + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            "query": query,
            'results': results
        }
    )

luna/blog/templates/blog/base.html
{% load content_tags static bulma_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tenor+Sans">
        <style>
            body {
                font-family: "Tenor Sans";
                background-color: #232323;
            }
            input.input, .textarea {
                background-color: #232323;
                color: #dedede;
            }
            p.indented {
                text-indent: 30px;
            }
            aside.menu li a:hover {
                background-color: #232323;
            }

        </style>
    </head>
    <body>
        <nav class="navbar is-black">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{% static 'imgs/logo.png' %}" alt="Logo" width="112" height="28">
                </a>
                <div class="navbar-burger burger" data-target="navbarMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="navbar-start is-black">
                <a class="navbar-item" href="/">Home</a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">More</a>

                    <div class="navbar-dropdown has-background-black has-text-white">
                        <a class="navbar-item" href="#">Museletter</a>
                        <a class="navbar-item" href="#">Community Discord</a>
                        <a class="navbar-item" href="#">Contact</a>
                    </div>
                </div>
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        {% if request.user.is_authenticated %}
                        <p class="control">
                            <a class="button is-danger is-medium is-outlined" href="{% url 'logout '%}">Admin Logout</a>
                        </p>
                        {% else %}
                        <p class="control">
                            <a class="button is-primary is-outlined is-medium" href="#">Submissions</a>
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <section class="section">
            <div class="container">
                <div class="columns is-centered">
                    <div class="column is-9">
                        {% block content %}
                        {% endblock %}
                    </div>
                    <div class="column is-3 is-vcentered">
                        <aside class="menu box has-background-black">
                            {% block sidenav %}
                            {% endblock %}
                            <hr> 
                            {% show_latest_posts %}
                            <hr>
                            <h4 class="menu-label has-text-white">Popular posts</h4>
                            {% get_most_commented_posts as most_commented %}
                            <ul class="menu-list">
                                {% for post in most_commented %}
                                <li><a class="has-text-white" href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                                {% endfor %}
                            </ul>
                            <hr>
                            <h4 class="menu-label has-text-white has-text-weight-semibold">Home to {% total_posts %} independent publications thus far!</h4>
                        </aside>
                        <div class="buttons">
                            <a class="button is-block is-fullwidth is-light is-outlined" href="{% url 'blog:posts_feed' %}">Subscribe to RSS Feed</a>
                            <a class="button is-block is-fullwidth is-info" href="#">Join the MuseLetter Mail List</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="footer has-background-black">
            <div class="container has-text-centered has-text-white">
                <p>hello</p>
            </div>
        </footer>
        <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.js">

        </script>
        <script>
            const csrftoken = Cookies.get('csrftoken');
            document.addEventListener('DOMContentLoaded', () => {
                (document.querySelectorAll('.notification .delete') || []).forEach($delete) => {
                    const $notification = $delete.parentNode;

                    $delete.addEventListener('click', () => {
                        $notification.parentNode.removeChild($notification);
                    });
                }
            {% block domready %}
            {% endblock %}
            });
            
        </script>
        {% block extra_js %}
        {% endblock %}
    </body>
</html>